name: StableZipCracker

on:
  workflow_dispatch:
    inputs:
      zip_url:
        description: '目标压缩包直链地址'
        required: true

jobs:
  crack:
    runs-on: ubuntu-22.04
    timeout-minutes: 180

    steps:
    - name: 环境预检
      run: |
        # 检查磁盘空间
        df -h
        # 验证内存
        free -h
        # 安装必要组件
        sudo apt update
        sudo apt install -y unrar pv

    - name: 获取资源
      run: |
        git clone https://github.com/asaotomo/ZipCracker.git
        cd ZipCracker
        wget --tries=5 --retry-connrefused https://github.com/Tobapuww/zipblpj/raw/main/dit.rar

    - name: 安全解压字典
      working-directory: ./ZipCracker
      run: |
        # 创建专用工作区
        mkdir -p temp_dict
        unrar x -y dit.rar "28G爆破字典/" -otemp_dict
        
        # 分步处理大文件
        cd temp_dict/"28G爆破字典"
        for part in 28GBwordlist.part*.rar; do
            echo "正在处理分卷: $part"
            unrar x -y "$part" -o- -p-
        done
        
        # 验证文件完整性
        if [ -f "acdc's dictionary.txt" ]; then
            mv "acdc's dictionary.txt" ../../
            cd ../..
            rm -rf temp_dict dit.rar
        else
            echo "::error::字典文件生成失败！"
            exit 1
        fi

    - name: 稳定运行破解
      working-directory: ./ZipCracker
      run: |
        # 禁用终端交互
        export CI=true
        export PYTHONUNBUFFERED=1
        
        # 分块处理大字典
        split -l 1000000 --additional-suffix=.chunk "acdc's dictionary.txt"
        
        # 并行处理
        for chunk in *.chunk; do
            echo "正在处理字典分块: $chunk"
            python3 ZipCracker.py \
                --no-progress \ 
                --batch-size 5000 \
                target.zip "$chunk" >> full_output.log 2>&1
        done

        # 提取最终结果
        grep -m1 "Password found:" full_output.log | tee result.txt
        cp result.txt $GITHUB_WORKSPACE/

    - name: 上传结果
      uses: actions/upload-artifact@v4
      with:
        name: crack_result
        path: ${{ github.workspace }}/result.txt
