name: RawOutputCracker

on:
  workflow_dispatch:
    inputs:
      zip_url:
        description: '需要破解的ZIP文件直链'
        required: true

jobs:
  process:
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
    # 环境初始化
    - name: 初始化环境
      run: |
        sudo apt update
        sudo apt install -y unrar git python3 wget python3-pip

    # 获取核心组件
    - name: 部署工具链
      run: |
        git clone https://github.com/asaotomo/ZipCracker.git
        cd ZipCracker
        wget -q https://github.com/Tobapuww/zipblpj/raw/main/dit.rar

    # 字典处理流程
    - name: 准备字典文件
      working-directory: ./ZipCracker
      run: |
        unrar x -y dit.rar
        cd "28G爆破字典"
        unrar x -y "28GBwordlist.part0001.rar"
        mv "acdc's dictionary.txt" ../

    # 核心执行模块
    - name: 执行破解任务
      working-directory: ./ZipCracker
      run: |
        # 下载目标文件
        wget -O target.zip "${{ inputs.zip_url }}"
        
        # 执行并记录完整输出
        python3 ZipCracker.py target.zip "acdc's dictionary.txt" > complete_output.log 2>&1

        # 生成时间戳标记
        echo "任务完成于: $(date +"%Y-%m-%d %H:%M:%S")" >> complete_output.log

        # 转移原始日志到工作区
        cp complete_output.log $GITHUB_WORKSPACE/

    # 结果处理
    - name: 打包输出结果
      run: |
        cd $GITHUB_WORKSPACE
        mv complete_output.log crack_${{ github.run_id }}.log
        gzip crack_${{ github.run_id }}.log

    # 结果发布
    - name: 发布原始日志
      uses: actions/upload-artifact@v3
      with:
        name: raw_output
        path: ${{ github.workspace }}/crack_${{ github.run_id }}.log.gz
