name: RawOutputCracker

on:
  workflow_dispatch:
    inputs:
      zip_url:
        description: '需要破解的ZIP文件直链'
        required: true

jobs:
  process:
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
    - name: 创建工作区
      run: |
        sudo mkdir -p /mnt/workspace
        sudo chown -R runner:docker /mnt/workspace
        echo "WORKSPACE=/mnt/workspace" >> $GITHUB_ENV
        
    # 环境初始化
    - name: 初始化环境
      run: |
        sudo apt update
        sudo apt install -y unrar python3 wget

    # 获取核心组件
    - name: 部署工具链
      run: |
        git clone https://github.com/asaotomo/ZipCracker.git
        cd ZipCracker
        wget -q https://github.com/Tobapuww/zipblpj/raw/main/dit.rar

    # 字典处理流程
    - name: 准备字典文件
      working-directory: ./ZipCracker
      run: |
        unrar x -y dit.rar
        cd "28G爆破字典"
        unrar x -y "28GBwordlist.part0001.rar"
        mv "acdc's dictionary.txt" ../
        cd ..
        rm -rf "28G爆破字典" dit.rar

    # 核心执行模块
    - name: 执行破解任务
      working-directory: ./ZipCracker
      run: |
        wget -O target.zip "${{ github.event.inputs.zip_url }}"
        python3 ZipCracker.py target.zip "acdc's dictionary.txt" > complete_output.log 2>&1
        echo "任务完成时间: $(date +'%Y-%m-%d %H:%M:%S %Z')" >> complete_output.log
        mv complete_output.log $GITHUB_WORKSPACE/

    # 结果发布（使用新版Action）
    - name: 上传原始日志
      uses: actions/upload-artifact@v4
      with:
        name: raw_logs
        path: ${{ github.workspace }}/complete_output.log
